### ISSUE TITLE
Politicians with existing, full P39 "position held" statements

### ISSUE THREAD

**Issue by siwhitehouse** [mysociety/verification-pages#105]
The following politicians are sitting waiting to be actioned, but they already have at least one full P39 statement for their position in the legislature. Actioning them is liable to create duplicate P39s

| Name | Legislature | Transaction ID
| --- | --- | --- |
| John Martin | British Columbia | 196554544269148
| Andrew Weaver | British Columbia | 150251572340230
| Ralph Bruce Fitch | New Brunswick | 499402667122637
| Ross Wetmore | New Brunswick | 192738511457579
| Benoît Bourque | New Brunswick | 187518105233437
| Rosa D'Amelio | Campania | 2058958151058170

**Comment by JenMysoc** [comment]
Adding in some I found today from House of Commons Canada:

| Name | District | Transaction ID
| --- | --- | --- |
| Andrew Leslie | Orléans | 164714427400202
| Karen Ludwig | New Brunswick Southwest | 1864897490417566
| James Moloney | Etobicoke--Lakeshore | 247059492501764
| Robert Sopuck | Dauphin--Swan River--Neepawa | 410325909426610
| Gordon Hogg | South Surrey--White Rock | 2023517691220233
| Bev Shipley | Lambton--Kent--Middlesex | 1816921111934506
| T. J. Harvey | Tobique--Mactaquac | 543844715987612
| Will Amos | Pontiac | 363438750800610
| Rob Nicholson | Niagara Falls | 1029425897223571
| Brian May | Cambridge | 1629079227209142
|

**Comment by JenMysoc** [comment]
Adding some in from Quebec National Assembly:

| Name | District | Transaction ID
| --- | --- | --- |
| Julie Bouley | Laviolette | 145056332856505 
| Carlos Leitão | Robert-Baldwin | 170465797005712
| Julie Bouley | Laviolette | 449411345489990
| Gabriel Nadeau Dubois | Gouin | 310924679439984

**Comment by JenMysoc** [comment]
Adding some from BC legislative assembly:

| Name | District | Transaction ID
| --- | --- | --- |
| John Martin | Chilliwack | 196554544269148 
| Andrew Weaver | Oak Bay-Gordon Head | 150251572340230

**Comment by JenMysoc** [comment]
also from New Brunswick: 
| Ralph Bruce Fitch | Riverview | 499402667122637
| Ross Wetmore | Gagetown-Petitcodiac | 192738511457579
| Benoît Bourque | Kent South | 187518105233437

**Comment by JenMysoc** [comment]
From Campania, Italy - Regional Assembly:

| Name | District | Transaction ID
| --- | --- | --- |
| Erasmo Mortaruolo | Benevento | 366399323862462
| Gennaro Oliviero | Caserta | 2048822655147012
| Francesco Picarone | Salerno | 165717697447011

**Comment by tmtmtmtm** [comment]
I've migrated all these to the Wiki instead: https://github.com/mysociety/verification-pages/wiki/Existing-full-P39-problems
