### ISSUE TITLE
Reporting two P39s, even when one has ended

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/verification-pages#154]
On the [16th Lok Sabha page](https://www.wikidata.org/wiki/User:Verification_pages_bot/verification/in/Member_of_the_16th_Lok_Sabha), [Haribhai Parthibhai Chaudhary](https://www.wikidata.org/wiki/Q16186182) is listed as "manually actionable" due to having two P39s:
![hpc vp](https://user-images.githubusercontent.com/57483/41955275-50e0684e-79d7-11e8-80ed-9e30c77b0c84.png)

The text given states that "one or of them might be missing an end date or parliamentary term qualifier" implies that this is only looking for "open" memberships, but in Wikidata he only has one of those, the other does have an end time:

![hpc wd](https://user-images.githubusercontent.com/57483/41955281-52bf996e-79d7-11e8-96d3-2bc5b7221fba.png)

**Comment by gbp** [comment]
I believe this is related to #186. Expect for this person we have two P39s so the statement ended up in manually actionable.

The fixes for #186 (PRs: #190 and #193) seem to have fixed this also :)
