### ISSUE TITLE
Make verification buttons more consistent

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/verification-pages#174]
![screen shot 2018-06-28 at 11 07 53](https://user-images.githubusercontent.com/57483/42028220-8e44051e-7ac3-11e8-957d-f9d6758fb2d1.png)

I find these buttons are a little jarring: they're meant to be the person's "answer" to the yes/no question above, but the "type" of answer isn't consistent across each, and the "Yes, but…" one seems odd, as there are lots of other potential "not quite right" scenarios: what if the party or area name is mis-spelled? What if one or both of those is wrong? 

I'm not sure how much of this just about putting better text on the labels, how much is about moving elements about, and how much requires quite deep rethinking of what we actually *do* in some of these cases, so it might be worth splitting this ticket up if there are quick wins we can do at one level even as a temporary improvement whilst we look at the deeper issues.

**Comment by zarino** [comment]
Problems here:

* "provide evidence" is really weird wording – what does it mean?
* "this position" is tech jargon – can we use a plain english summary of the position instead, like "[person] is [job title] for [district]?"
* "yes, verify" is very weird wording – we haven’t used "verify" anywhere else in the text
* ISTR there was talk of dropping the "name isn’t quite right" option. If we do, I guess we still need to explain to people which button they should click if the person / party / district names aren’t identical?
