### ISSUE TITLE
Add additional Reference qualifiers

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/verification-pages#175]
Currently references that get created in Wikidata only get a P854 (reference URL) qualifier:

![screen shot 2018-06-28 at 11 24 23](https://user-images.githubusercontent.com/57483/42028975-e007b2c2-7ac5-11e8-8b61-841128fd6a30.png)

Ideally references would also be given other qualifiers per https://www.wikidata.org/wiki/Help:Sources#Web_page. Most of these would need to be set up at the point of creating the URL, but P813 (date retrieved) could be presumed to be the date that the verification happens.

**Comment by gbp** [comment]
@tmtmtmtm #211 adds the date retrieved and makes it easier to add other reference qualifiers. Which other ones would you like to have: `title` (P1476) and `language of work or name` (P407) seem like the most appropriate ones?

**Comment by tmtmtmtm** [comment]
Yep, title and language seem like the most appropriate to add for now. We can add new issues for any others later.
