### ISSUE TITLE
Page should default to showing things that need done

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/verification-pages#179]
When I load the [16th Lok Sabha page](https://www.wikidata.org/wiki/User:Verification_pages_bot/verification/in/Member_of_the_16th_Lok_Sabha) , the first thing I'm shown is a statement that matches the data on Wikidata:

![screen shot 2018-06-28 at 14 32 45](https://user-images.githubusercontent.com/57483/42037420-49a67dd4-7ae0-11e8-9347-e12f651457e6.png)

The page should, by default, show me things that actually need done, rather than me having to go looking for those.

**Comment by zarino** [comment]
This feels like less of a problem now that [by default, you see _all_ statements in a table](0206ec75faabb83b92dad4b81212beea22ce4971)
