### ISSUE TITLE
Add Wikipedia source where not everyone is reconciled

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/verification-pages#183]
https://morph.io/everypolitician-scrapers/switzerland-national-council-members-50-wikipedia has a single member not yet reconciled to Wikidata, so should be a good example of testing out the flow for that scenario. All parties and constituencies are reconciled.

**Comment by gbp** [comment]
This page has been created:
https://www.wikidata.org/wiki/User:Verification_pages_bot/verification/ch/Memeber_of_the_50th_National_Council

**Comment by tmtmtmtm** [comment]
@gbp thanks for this, though you have a typo in the name "Memeber" rather than "Member". Is that easy to change?

**Comment by gbp** [comment]
@tmtmtmtm yep fixed.

**Comment by tmtmtmtm** [comment]
Thanks!
