### ISSUE TITLE
An existing P39 with a start date before the start of the given term should not be extended

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/verification-pages#186]
The [CH50 page](https://www.wikidata.org/wiki/User:Verification_pages_bot/verification/ch/Memeber_of_the_50th_National_Council) took a pre-existing P39, with a start date quite a while before the start of the 50th National Council:

![screen shot 2018-06-29 at 11 30 20](https://user-images.githubusercontent.com/57483/42088160-83fca07a-7b90-11e8-9aea-579941364b0e.png)

and [added](https://www.wikidata.org/w/index.php?title=Q1646725&type=revision&diff=704088132&oldid=630631901) a parliamentary term and electoral district to it:

![screen shot 2018-06-29 at 11 36 14](https://user-images.githubusercontent.com/57483/42088193-a7a80d16-7b90-11e8-8912-b3e738343d9b.png)

This is not only creating inconsistent data (it implies that 1 December 2003 is within the timeframe of the 50th National Council), it is also creating data that might not be true (e.g. if he had represented a different district in the previous term).

**Comment by tmtmtmtm** [comment]
I have [reverted](https://www.wikidata.org/w/index.php?title=Q1646725&type=revision&diff=704089980&oldid=704088132) this change on Wikidata.

**Comment by tmtmtmtm** [comment]
Other examples of this in the terms we've created data for so far, which will need to be resolved: http://tinyurl.com/y9dhjb3b

**Comment by tmtmtmtm** [comment]
Unfortunately this didn't really fix the problem: it now creates an entirely new duplicate statement for someone where there shouldn't be anything to do:

![screen shot 2018-06-29 at 16 18 20](https://user-images.githubusercontent.com/57483/42100843-3d86f72a-7bb9-11e8-8f67-a8bf874d85f3.png)

plus

![screen shot 2018-06-29 at 16 18 14](https://user-images.githubusercontent.com/57483/42100839-3c2c6b44-7bb9-11e8-8cf3-9dce6b397386.png)

[becomes](https://www.wikidata.org/w/index.php?title=Q21181009&type=revision&diff=704189886&oldid=703839555):

![screen shot 2018-06-29 at 16 27 02](https://user-images.githubusercontent.com/57483/42100867-4fde32e4-7bb9-11e8-96ac-2371a868d0a0.png)

**Comment by gbp** [comment]
@tmtmtmtm have deployed a [change](https://github.com/mysociety/verification-pages/pull/193/commits/707cdefee7f789413f5348434d2212ce934c86d8) we hope will fix this.
