### ISSUE TITLE
create a bot account for generating verification pages

### ISSUE THREAD

**Issue by mhl** [mysociety/verification-pages#20]
We did discuss with @tmtmtmtm whether we could create a new account, perhaps "Everypolitician_pages_bot" which generically has permission to create and edit *pages*, but not items. (Or we could request an extension of one of the existing bot's permissions: at the moment we have:
* Position_holder_history_bot
* Politican_scraper_comparison_bot
* Prompter_Bot
* PositionStatements_Bot

Or we could just create a new account for this, called Verification_pages_bot

**Comment by chrismytton** [comment]
Have taken the easier route for now and created a new account: [User:Verification pages bot](https://www.wikidata.org/wiki/User:Verification_pages_bot). Haven't requested a bot flag yet, not sure if we need one if we're just updating pages, rather than items?

**Comment by chrismytton** [comment]
Password for the bot is on the internal wiki.
