### ISSUE TITLE
Filter position statements belonging to previous terms

### ISSUE THREAD

**Issue by gbp** [mysociety/verification-pages#212]
While investigating #205 it appears the current SPARQL query can return position statements belonging to previous terms. We should to add `FILTER` to remove these.

**Comment by gbp** [comment]
@tmtmtmtm do you reckon we can craft a new SPARQL query to see if this has changed any data it should've?

**Comment by gbp** [comment]
@mhl I think due to these [lines](https://github.com/mysociety/verification-pages/blob/master/app/javascript/wikiapi.js#L82-L90) this wouldn't of caused any accidental changes. Would you agree?

**Comment by mhl** [comment]
I think you're right, yes :+1:
