### ISSUE TITLE
A means of displaying completion of current verification-page

### ISSUE THREAD

**Issue by rich-cassidy** [mysociety/verification-pages#219]
The verification-pages currently display a total of all suggestions for that particular page, and opening the filter will display the numbers of suggestions against a particular status, but there's no quick overview of how much of verification process has been completed for a particular page.

**Comment by zarino** [comment]
@rich-cassidy Given the tool in its current state (where all statements are visible on the page at once, by default) is this still a pain point for you?

**Comment by rich-cassidy** [comment]
Not as much, and I'm also now struggling to think of a more general use case for it right now

**Comment by rich-cassidy** [comment]
@zarino Sorry, forgot to tag you above

**Comment by tmtmtmtm** [comment]
The dropdown also now gives you a total of how many statements are currently at that status:

![screen shot 2018-07-23 at 21 53 43](https://user-images.githubusercontent.com/57483/43102385-e8e683f8-8ec2-11e8-8f21-2157b67ceece.png)
