### ISSUE TITLE
Allow users to choose to work on 'easy' or 'hard' suggestions

### ISSUE THREAD

**Issue by rich-cassidy** [mysociety/verification-pages#220]
As the user base of the tool is potentially quite broad, it would be helpful to enable users to be able to choose/filter the suggestions based on the suggestions' 'difficulty'.

For example, suggestions which seem to have neatly been matched to the relevant properties in Wikidata and require a more simply 'yes they appear in this source URL' or 'no they don't' input could be distinguished from those where there's more rationalising with Wikidata to be done.

**Comment by tmtmtmtm** [comment]
I think this is less valuable now with the newer interface
