### ISSUE TITLE
Verify/reconcile via a table UI, so you can see all position holders in a list, rather than one at a time

### ISSUE THREAD

**Issue by rich-cassidy** [mysociety/verification-pages#221]
At the moment, users must step through suggestions one at a time.

Providing users with the ability to progress suggestions through the workflow within the table itself gives users the ability to work down a list with a tangible sense of progress, be able to quickly see which suggestions need attention, and be able to work on any suggestions they feel they can work on.

**Comment by zarino** [comment]
Considerations:

* Ideally there should be some way to sort the table (see #218 and #217)
* Ideally there should be some way to _filter_ the table, so only people at a certain stage (eg: `manually_actionable`) are visible, and then a way to easily remove the filter
