### ISSUE TITLE
Reconciling a party/constituency to a Wikidata ID once should apply throughout the page

### ISSUE THREAD

**Issue by rich-cassidy** [mysociety/verification-pages#224]
During the reconciliation stage, the same parties or constituencies have an opportunity to appear multple times on the same page.

They will often be spelled the same throughout the set, so it’d be a waste to make someone "reconcile" the exact same text a number of times over.

If a party or constituency in the suggestion table is unmatched to a Wikidata ID, and is then matched to a Wikidata ID, the suggestions in the table with the respective party or constituency which has now been matched should update to reflect that change.

Possibly a follow-on from #223

**Comment by tmtmtmtm** [comment]
Not having to reconcile the same district more than once is needed for:
* https://www.wikidata.org/wiki/User:Verification_pages_bot/verification/no/Member_of_the_2017_Storting
