### ISSUE TITLE
Provide the ability to amend a pre-matched constituency/party

### ISSUE THREAD

**Issue by rich-cassidy** [mysociety/verification-pages#226]
Pre-matching the party and constituency of a suggestion to their Wikidata ID will be enormously helpful, but there may be times when some nuance has been missed and a wrong match made. Allowing users to correct this means these cases can be handled within the tool (rather than being dealt with as exceptions behind the scenes)

**Comment by tmtmtmtm** [comment]
@rich-cassidy this looks like a duplicate of #194
