### ISSUE TITLE
Existing start dates after the end of the previous term should not be treated as problematic

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/verification-pages#236]
It is very common that P39 statements already exist with a P580 qualifier set to, for example, the date of the relevant election. Currently this will cause a claim to be marked as requiring manual action:

![screen shot 2018-07-06 at 16 27 20](https://user-images.githubusercontent.com/57483/42387285-c0959056-8139-11e8-9f51-7686169dd3c7.png)

In the spirit of Postel, I think we should only declare a clash if the date is before the end date of the previous term, rather than the start date of the current one (assuming that's available of course; where it's not we should still use the start of the current term)

**Comment by tmtmtmtm** [comment]
(NB: this isn't a great example, as the 15th Lok Sabha ended on May 18th, so this statement would still be problematic!)

**Comment by tmtmtmtm** [comment]
I think the existing cases of this will have been fixed by #301

We may still have a version of this where there's a longer gap between terms, but for now I'm going to mark this as closed, and we can re-open if we actually see it happening.

**Comment by tmtmtmtm** [comment]
@siwhitehouse has now found a case where this is still problematic. The [42nd Canadian Parliament](https://www.wikidata.org/wiki/Q21157957) has a start date of 3 December 2015. The [41st](https://www.wikidata.org/wiki/Q2816776) had an end date of 2 August 2015. Many members already have a P39 with a start date of 19 October 2015, which was the election:

![screen shot 2018-07-24 at 08 57 08](https://user-images.githubusercontent.com/57483/43124643-9ec3677a-8f1f-11e8-9812-c0255af9419d.png)

As this is more than a month before the actual start date of the term, we're [creating duplicate P39s](https://www.wikidata.org/w/index.php?title=Q21713417&type=revision&diff=714615236&oldid=714192120) in such cases.

**Comment by siwhitehouse** [comment]
This is also affecting some statements in the [29th Alberta Legislative assembly](https://www.wikidata.org/wiki/Q19876139). The election was on 5th May 2015 and the legislature's inception date was 15th June 2015

**Comment by tmtmtmtm** [comment]
This is also true for https://github.com/mysociety/verification-pages/issues/236, where many members have an existing P580 of 29 October 2016, but the term itself has a start date of 6 December 2016

**Comment by siwhitehouse** [comment]
https://www.wikidata.org/wiki/User:Verification_pages_bot/verification/ca#s:2069887239914958 and https://www.wikidata.org/wiki/User:Verification_pages_bot/verification/ca#s:435661013520177 are also affected by this issue.

**Comment by gbp** [comment]
In the end I don't think there is anything left to do here. I think this got resolved with the new membership-comparison gem and this is covered by https://github.com/everypolitician/membership-comparison/blob/master/spec/membership_comparison_spec.rb#L260-L277
