### ISSUE TITLE
Only common fields should be compared

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/verification-pages#238]
The [50th UK Parliament page](https://www.wikidata.org/wiki/User:Verification_pages_bot/verification/in/Member_of_the_50th_Parliament_of_the_United_Kingdom) marks everyone as requiring manual intervention, noting that the electoral district on Wikidata differs from that in the source. However, this is because the source CSV here does not provide an electoral district for anyone.

Where a field is provided by both sources, and differs, highlighting that is definitely a good thing. But when only one source provides it, I'm not so sure that we should be comparing them.

**Comment by chrismytton** [comment]
https://github.com/mysociety/verification-pages/pull/308 is now live which fixes this specific issue, but I'm going to leave this ticket open as it doesn't handle anything other than district at the moment.

**Comment by siwhitehouse** [comment]
https://www.wikidata.org/wiki/User:Verification_pages_bot/verification/ca#s:704180573253870 is affected by this issue. In this case the parliamentary group is missing in the source.

**Comment by chrismytton** [comment]
@gbp Can this be closed now that https://github.com/mysociety/verification-pages/pull/435 has been merged?
