### ISSUE TITLE
Cron tasks to load statements for each page periodically

### ISSUE THREAD

**Issue by gbp** [mysociety/verification-pages#29]

**Comment by mhl** [comment]
This refers to bringing statements from suggestions-store into the verification-pages DB.

**Comment by gbp** [comment]
This can be done by running: `rails verification_page:load:all`

**Comment by chrismytton** [comment]
I've set this up to run on Heroku Scheduler. It runs once a day at 05:00 UTC. This schedule can be adjusted by running `heroku addons:open scheduler --app verification-pages`, which will open a web page where you can change the frequency and times that this job will run.

**Comment by chrismytton** [comment]
Going to leave this ticket open for now so that when we do #7 and get this running on Toolforge I remember to setup cron on there as well.

**Comment by chrismytton** [comment]
This is setup on Toolforge now.
