### ISSUE TITLE
sort countries when creating a new page

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/verification-pages#290]
The drop down list of countries when creating a new Verification Page currently doesn't seem to be in any useful order (creation order, perhaps?):

![screen shot 2018-07-18 at 09 29 51](https://user-images.githubusercontent.com/57483/42869552-4adcc1f8-8a6d-11e8-8a32-45648326e192.png)

This should probably be sorted alphabetically.

**Comment by gbp** [comment]
Closing now #612 is merged and deployed
