### ISSUE TITLE
Remove suggestions that vanish from the source

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/verification-pages#316]
If a scraper no longer provides a suggestion, we shouldn't continue to offer it for verification: the page should always reflect only the data currently provided by the source.

**Comment by mhl** [comment]
I think it would be nice for these suggestions that have disappeared if we noticed they'd gone and had a new type of statement call-to-action, which would be something like: "Set an end date?" or "This was never true". (This might work well as a way of handling errors that have been reported via suggestions-store as well.)
