### ISSUE TITLE
seamus oreagan #329740470872589 is not reconcilable

### ISSUE THREAD

**Issue by siwhitehouse** [mysociety/verification-pages#321]
We have already created a P39 statement for https://www.wikidata.org/wiki/Q7440780 (Seamus O'Regan). This transaction is presumably not reconciling because of the lower case name and/or lack of apostrophe.
Seamus is a member of the Canadian House of Commons

**Comment by tmtmtmtm** [comment]
@siwhitehouse is this a duplicate of https://github.com/mysociety/verification-pages/issues/148?

**Comment by siwhitehouse** [comment]
Yes. Sorry, I'd missed Georgie's earlier issue
