### ISSUE TITLE
Cathy Wagantal #1775788095793842 is a misspelled name

### ISSUE THREAD

**Issue by siwhitehouse** [mysociety/verification-pages#324]
We have already added a P39 statement to https://www.wikidata.org/wiki/Q22116843 (Cathy Wagantall).
Cathy is an MP in the Canadian House of Commons and this transaction is currently in 'reconcilable'.

**Comment by tmtmtmtm** [comment]
Migrated to https://github.com/mysociety/verification-pages/wiki/Manual-fixes-dumping-ground
