### ISSUE TITLE
decide what to do about parties / parliamentary groups generally

### ISSUE THREAD

**Issue by mhl** [mysociety/verification-pages#35]

**Comment by tmtmtmtm** [comment]
This will be more of an issue now that we're getting data from Wikipedia, where we will usually have party/group information. We'll probably need to split this ticket up into a variety of smaller ones for being _able_ to reconcile; making sure that each party only needs reconciled once per page; etc — but we'll let those arise naturally and ticket them as they come up.

**Comment by tmtmtmtm** [comment]
see #151, #162
