### ISSUE TITLE
When searching during reconciliation hitting <enter> should trigger the search

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/verification-pages#353]
In the new reconciliation search introduced in #352, hitting [enter] in the search-string box has no obvious effect, when I would expect it to trigger the search. Currently I need to actively click the "Update results" button

![image](https://user-images.githubusercontent.com/7907/43135523-9d41764e-8f3d-11e8-9804-f2d95c55f91a.png)

**Comment by mhl** [comment]
Fixed in cf2e26564bfdb26f1d0f
