### ISSUE TITLE
make it more obvious what needs to be reconciled and how to switch to do that

### ISSUE THREAD

**Issue by mhl** [mysociety/verification-pages#357]
We're considering a new design for the first row of each statement, so that it's clearer what needs to still be reconciled, and how to switch to doing that. The proposed design (below) would also have the advantage that the first row always shows the names from the CSV file, while below we would show the reconciled name (i.e. the label the reconciled Wikidata item has)

![new doc 2018-07-23_2](https://user-images.githubusercontent.com/7907/43147450-f82a511c-8f5a-11e8-8e97-f5bc899505ab.jpg)

**Comment by tmtmtmtm** [comment]
This was closed by 0bb720a86c4d08c179eee03654df80f236699a89 &co
