### ISSUE TITLE
Don't show "finished" statements in the static "New statements to verify" section

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/verification-pages#388]
Currently this appears to show all statements, no matter their status. 

Making it only include statements where something can be done will not only be more useful in the case where someone _doesn't_ have the Javascript installed, but will also mean adding the page to your Watchlist will be more useful.

**Comment by chrismytton** [comment]
Just to clarify, the way things currently work is that there are multiple heading on the static page with statements underneath, with the following headings:

- New statements to verify
- Statements which are unverifiable
- Statements to reconcile
- Statements to action
- Statements requiring manual intervention
- Statements already verified & reconciled

So when a statement is finished it moves to under the "Statements already verified & reconciled" heading. This will already trigger a watchlist notification, and it should be reasonably obvious from the diff that something is moving between sections.

Do we still want to remove the "Statements already verified & reconciled" section?

**Comment by tmtmtmtm** [comment]
Yep: the underlying issue here is actually #390 causing the pages to not update, so I don't think we need to change this now (at least not in this way: there are still improvements we want to make to this view, but we can handle those separately)
