### ISSUE TITLE
Allow some suggestions from Facebook crowdsourcing to not require a legislative term

### ISSUE THREAD

**Issue by rich-cassidy** [mysociety/verification-pages#396]
When Facebook users are suggesting UK local councillors, for example, they will only be suggesting that a councillor is currently in office, and not suggesting the particular election cycle a UK local councillor was elected in and thus which term they're associated with. We know that the UK local councillors are a deifnite use case of this because a third of councillors are elected at a time.

**Comment by tmtmtmtm** [comment]
@rich-cassidy is this already covered by #67, or is this slightly different to that? e.g. are you suggesting that there may be cases where we have neither a term _nor_ a start date?

**Comment by tmtmtmtm** [comment]
@rich-cassidy I think that's going to be very difficult to handle, as there isn't really any way in Wikidata to say that someone is a current member without having either a start date or a term with which to qualify their P39. Per #67, that's probably going to have to mean that someone (either at the time of doing the verification, if everyone's membership is completely out of sync, or at the time of creating the page if a group of members all get elected at essentially the same time) is going to have to provide one or the other.

So, for example, in a case where one third of members get elected together, the person doing the verifying would either need to say for each person which cohort they were elected as part of; or there could be three verification pages set up, one for each of the three plausible elections, each with a distinct start-date (and potentially a separate reference URL).
