### ISSUE TITLE
Bulk create every Country

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/verification-pages#402]
Setting a Country for a page that doesn't have one yet is quite a bit of extra friction that could be entirely automated. We could fetch everything Wikidata knows as a country, set the English description to "politician in [country name]", and default the label language to 'en' (which someone can change on a case by case basis as/when needed, though we should probably move that to be page-specific rather than country-specific anyway, see #401)

**Comment by chrismytton** [comment]
Useful context from the duplicate linked to above:

>Name: the en label for the country in Wikidata
>Code: can be found via P297
>Description en: we can make this "Politician in {Name as above}"
>Label lang: this is trickier, because really we should change the label lang depending on the language of the CSV source - until that change is made, we could default to one of the official languages of the country P37 -> P424
>Wikidata: the Wikidata ID of the country
>
>I'm sure this can be improved, but a query like this would be a start: http://tinyurl.com/y9g69kvg

**Comment by tmtmtmtm** [comment]
Note that this would really only be a stopgap, and https://github.com/mysociety/verification-pages/issues/459 would be a much better solution.

**Comment by gbp** [comment]
Closing now #612 is merged and deployed
