### ISSUE TITLE
Duplicate statement verification not handling reference_url

### ISSUE THREAD

**Issue by chrismytton** [mysociety/verification-pages#419]
This bit of code doesn't currently handle the `reference_url`. This should use the reference_url from the original verification so that the original and the duplicate both have the same reference URL.

https://github.com/mysociety/verification-pages/blob/2457a6f0ba7c18c4b277223f425349a06a90f726/app/models/statement.rb#L72-L75

**Comment by gbp** [comment]
Seeing errors for this:

```
I, [2018-09-13T10:26:32.027428 #6]  INFO -- : [755031d8-f43a-42e4-97fb-ca4cbd9d4fa0] Completed 422 Unprocessable Entity in 386ms (ActiveRecord: 106.0ms)
F, [2018-09-13T10:26:32.028315 #6] FATAL -- : [755031d8-f43a-42e4-97fb-ca4cbd9d4fa0]
F, [2018-09-13T10:26:32.028359 #6] FATAL -- : [755031d8-f43a-42e4-97fb-ca4cbd9d4fa0] ActiveRecord::RecordInvalid (Validation failed: Reference url can't be blank):
F, [2018-09-13T10:26:32.028384 #6] FATAL -- : [755031d8-f43a-42e4-97fb-ca4cbd9d4fa0]
F, [2018-09-13T10:26:32.028408 #6] FATAL -- : [755031d8-f43a-42e4-97fb-ca4cbd9d4fa0] app/models/statement.rb:69:in `verify_duplicate!'
[755031d8-f43a-42e4-97fb-ca4cbd9d4fa0] app/services/load_statements.rb:28:in `block in run'
[755031d8-f43a-42e4-97fb-ca4cbd9d4fa0] app/services/load_statements.rb:14:in `map'
[755031d8-f43a-42e4-97fb-ca4cbd9d4fa0] app/services/load_statements.rb:14:in `run'
[755031d8-f43a-42e4-97fb-ca4cbd9d4fa0] app/services/service_base.rb:6:in `run'
[755031d8-f43a-42e4-97fb-ca4cbd9d4fa0] app/controllers/pages_controller.rb:58:in `load'
```

**Comment by chrismytton** [comment]
Just for learning/general interest: this is causing a 422 error, whereas I would have expected a 500 error.

> The change you wanted was rejected.
> Maybe you tried to change something you didn’t have access to.

<img width="1382" alt="screen shot 2018-09-13 at 11 48 33" src="https://user-images.githubusercontent.com/22996/45484122-09399900-b74b-11e8-9234-73f52349708c.png">

It turns out that Rails has a mapping for some exception classes to specific HTTP response codes.

https://github.com/rails/rails/blob/0ae59ea828ed20141af0d4c9ed9130eb47ce55f3/activerecord/lib/active_record/railtie.rb#L22

So `ActiveRecord::RecordInvalid` maps to `:unprocessable_entity`, which means 422 is returned instead of 500 when that exception class is raised!
