### ISSUE TITLE
Send exceptions to email

### ISSUE THREAD

**Issue by chrismytton** [mysociety/verification-pages#446]
At the moment we don't know about any exceptions that occur on Toolforge. Ideally we should get an email anytime someone gets a 500-error.

We can either use the [exception_notification](https://rubygems.org/gems/exception_notification) gem to send errors directly to an email alias, or we can use something like [Rollbar](https://rollbar.com/) to track errors centrally, though that might be more overhead than we need here.

Related to #390 because ideally we should get emails about exceptions in cron jobs as well.

**Comment by gbp** [comment]
On Toolforge we're getting `An error occurred when sending a notification using 'email' notifier. Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 25`

**Comment by gbp** [comment]
Have tested the configuration suggested here: https://stackoverflow.com/questions/9748239/where-i-can-read-complete-manual-to-configure-smtp-for-rails/12815481#12815481

It works.
