### ISSUE TITLE
request a bot flag for Verification_pages_bot

### ISSUE THREAD

**Issue by mhl** [mysociety/verification-pages#451]
Now that you can create a verification page from a template tag on any wiki page, we need to request a bot flag for Verification_pages_bot in the usual way: https://www.wikidata.org/wiki/Wikidata:Requests_for_permissions/Bot

**Comment by tmtmtmtm** [comment]
I don't think we should request this until we've fixed the known cases where the tool creates duplicate data (e.g. #327 #236 #314 #48 †), and probably also #304, as these are issues that would justifiably lead to the bot being stopped, or even blocked. 

---
(† I also thought there was also an issue about the case of adding data from _before_ an existing statement, but I can't find that right now.)

**Comment by chrismytton** [comment]
I've started a bot flag request: [Wikidata:Requests_for_permissions/Bot/Verification_pages_bot](https://www.wikidata.org/wiki/Wikidata:Requests_for_permissions/Bot/Verification_pages_bot)

I haven't added it to [Wikidata:Requests_for_permissions/Bot](https://www.wikidata.org/Wikidata:Requests_for_permissions/Bot) yet, so feel free to make any edits you deem appropriate.

**Comment by chrismytton** [comment]
Request is now in: [Wikidata:Requests_for_permissions/Bot#Verification_pages_bot](https://www.wikidata.org/wiki/Wikidata:Requests_for_permissions/Bot#Verification_pages_bot)

**Comment by chrismytton** [comment]
There was a response from the admins with further questions which I have just replied to.

**Comment by chrismytton** [comment]
This has now been approved, hooray! 

https://www.wikidata.org/wiki/Wikidata:Requests_for_permissions/Bot/Verification_pages_bot
