### ISSUE TITLE
Country should be specified as Wikidata ID, not ISO code

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/verification-pages#458]
Currently, when creating a country, a user needs to specify a country code:

```
{{User:Chris_Mytton/sandbox/Template:Verification_page
|position_held_item=Q9045502
|parliamentary_term_item=Q55670426
|country_code=no
|csv_source_url=https://morph-csv-proxy.herokuapp.com/?scraper=everypolitician-scrapers/norway-stortinget-2017-wikipedia&query=select+name+as+person_name,+area+as+electoral_district_name,+id+as+person_item,+party_id+as+parliamentary_group_item,+party+as+parliamentary_group_name+from+data
}}
```

This is inconsistent with the other parameters, is error-prone (if someone guesses the country code incorrectly), or will often require the user to go look the code up, and it's unclear what to do if you're trying to set up a page for somewhere that doesn't *have* a country code. Instead, this should take a Wikidata Item id, as per the position and term parameters.

**Comment by gbp** [comment]
Closing now #613 is merged and deployed
