### ISSUE TITLE
allow customization of the reference URL that will be used

### ISSUE THREAD

**Issue by mhl** [mysociety/verification-pages#46]
In other words, let people override the default reference URL (typically a list page) that would otherwise be used.

**Comment by mhl** [comment]
In addition, it would be good to allow a `Page` to be created with `reference_url` NULL, to make it simpler to automate creation of `Page` objeccts. Then users could be left to find the reference URL themselves. (The first reference URL could be set in the database.)

**Comment by chrismytton** [comment]
> In addition, it would be good to allow a Page to be created with reference_url NULL, to make it simpler to automate creation of Page objeccts. Then users could be left to find the reference URL themselves. (The first reference URL could be set in the database.)

This was done in #404 and has now been deployed 🎉 



> In other words, let people override the default reference URL (typically a list page) that would otherwise be used.

A few more details about this:

- Add a "change reference URL" link to verifiable statement HTML
- Store the reference URL that's used to verify a statement in a new `reference_url` column in the `statements` table
- Store a log of the reference URLs in a separate table, like we're doing for verifications.
- Use localStorage to keep track of the URLs that are used so a user doesn't have to keep typing them in
