### ISSUE TITLE
block double-clicks of "update", since (for a new P39) it'll add it twice

### ISSUE THREAD

**Issue by mhl** [mysociety/verification-pages#48]

**Comment by tmtmtmtm** [comment]
@mhl is this still an issue with the current workflow (where data will automatically be added in most cases)?

**Comment by tmtmtmtm** [comment]
There are still cases where data needs to be submitted manually (e.g. after a bulk reconciliation), so I'm assuming this is still an active problem.

**Comment by gbp** [comment]
Having looked through this I don't think there is much needed for this as the changes made in 8041ef4e6cc1be5d3947528b5a9fa2b0c16368f8 this removes the button from view once the parent `loading` callback is triggered. This is done https://github.com/mysociety/verification-pages/blob/d92cb9f227e6f08ccfd1d8c980473e787fbbdb43/app/javascript/components/actionable.js#L109 but could be moved to the start of the function.
