### ISSUE TITLE
run the reconciliation search immediately after clicking "yes, verify"

### ISSUE THREAD

**Issue by mhl** [mysociety/verification-pages#49]
To be clear, i think it would be annoying if the search ran automatically when you're just flicking through the statements (and would make lots of pointless requests to the API) but if someone has just clicked on "Yes, verify", there's no reason not to run the search without an extra button click.

**Comment by tmtmtmtm** [comment]
I think this is fixed / superseded by the changes at 0bb720a86c4d08c179eee03654df80f236699a89
