### ISSUE TITLE
What next after "country: must exist" error?

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/verification-pages#498]
When trying to set up a new page I got an error:

![screen shot 2018-10-25 at 09 47 43](https://user-images.githubusercontent.com/57483/47487863-2b8b0000-d83b-11e8-837d-5e41e9323aea.png)

But there's nothing to tell me what I'm meant to do to resolve this.

**Comment by tmtmtmtm** [comment]
I've marked this as a blocker, because we can't actually release this until users can create pages for any legislature of their choice. The solution is likely to be to remove the requirement for a 'country' parameter entirely, however (e.g. #459), rather than giving better info here.

**Comment by gbp** [comment]
Closing now 3bedda42d4777eadd5a78dbf3b488ef38d25973d is merged and deployed
