### ISSUE TITLE
Clean and validate page title before saving

### ISSUE THREAD

**Issue by chrismytton** [mysociety/verification-pages#515]
We've just seen an error where statements weren't loading for a page because the `statements.json` endpoint was returning a 404 status. It turns out this was because the page's title had a space character at the beginning of it. This caused the lookup by title to fail.

I think we should do a couple of things:

- [ ] Strip any space from around the title before saving
- [ ] Validate that the page title doesn't contain any spaces (e.g. instead of a `_`, which we've bumped into in the past)

**Comment by tmtmtmtm** [comment]
@chrismytton is this essentially the same as #138?

**Comment by chrismytton** [comment]
Ah yes, so it is. I did try searching for existing tickets, clearly failed at that though!

Closing as this is a dupe of https://github.com/mysociety/verification-pages/issues/138
