### ISSUE TITLE
"new person" label should be configurable per-Page

### ISSUE THREAD

**Issue by tmtmtmtm** [mysociety/verification-pages#530]
Currently the label set on a newly created Wikidata Person Item is configured for an entire country, which means it's usually going to be something like "Indian politician". But, especially when dealing with a state or city legislature, we might want that to be something different on a Page by Page basis.

Moving this to the Page setup, rather than the Country setup, would also allow it to be under the control of normal users, rather than only admins.

**Comment by chrismytton** [comment]
Pull request: https://github.com/mysociety/verification-pages/pull/544
