### ISSUE TITLE
[Toolforge] Migrate to the Debian Stretch job grid

### ISSUE THREAD

**Issue by gbp** [mysociety/verification-pages#596]
This email is a reminder that the tools listed below have run jobs and/or
webservices using the Ubuntu Trusty job grid in the past 7 days. This job grid
will be shutdown on or before the week of 2019-03-25 as the final step in the
removal of Ubuntu Trusty from Toolforge and the larger Cloud VPS environment.

  * verification-pages

See <https://tools.wmflabs.org/trusty-tools/t/verification-pages> for more details
on these tools and the jobs that have been seen.

Please see the migration instructions on Wikitech [0] for more information on
how to move your tools to either the new Debian Stretch job grid or the
Kubernetes cluster.

\[0\]: https://wikitech.wikimedia.org/wiki/News/Toolforge_Trusty_deprecation

**Comment by gbp** [comment]
Similar issues for [position-holder-history](https://github.com/everypolitician/wmf-position-holder-history/issues/1) & [prompter](https://github.com/everypolitician/prompter/issues/9) /cc @chrismytton

**Comment by sagepe** [comment]
I've moved the two cronjobs to the Stretch grid ([instructions here](https://wikitech.wikimedia.org/wiki/News/Toolforge_Trusty_deprecation#Move_a_cron_job)), so hopefully this should be done.

**Comment by gbp** [comment]
Closing as migration has happened and everything seems to be running fine.
