### ISSUE TITLE
add a Country model

### ISSUE THREAD

**Issue by mhl** [mysociety/verification-pages#61]
There's various information we need for verification pages that's going to be the same for every verification page for a particular country, so we shouldn't have to repeat this on each Page object. For example we need:

* The default description for a newly created politician
* The language code of the newly created politician
* The one or more Wikipedias to search for existing people

It makes sense to me to create a Country model, and potentially also a Wikipedia model since we may want to search more than one Wikipedia per country. (e.g. for Canada both enwiki and frwiki perhaps?)

This could help in fixing #59

**Comment by chrismytton** [comment]
We've added the country model, but we still need to add the relation between pages and countries, so I'm going to reopen this issue.

I think we'll have to add the relation in several steps:

1. Add a nullable `country_id` column to `Page` and the appropriate macros to the model to tell Rails they're related
2. Write a script to update the `country_id` column for existing pages
3. Make the `country_id` column on `Page` required.
