### ISSUE TITLE
when actioning a statement it should be more clear what's going to happen

### ISSUE THREAD

**Issue by mhl** [mysociety/verification-pages#68]
When a statement is in the actionable state, it'll look like:

![action](https://user-images.githubusercontent.com/7907/37827379-2fcc7b40-2e8f-11e8-8324-55a7b2a5d9b4.png)

.... but at the moment that'll look the same regardless of whether it's going to create a whole new P39 with those details, update a bare existing one, or perhaps just add the reference URL to an existing one.

I've been finding it annoying having to look at the person's wikidata page and back to trying and guess which of those will happen, but it could be done automatically.

**Comment by tmtmtmtm** [comment]
I'd prefer we either hide this information by default (only revealing it if explicitly requested), or, even better, remove the need for there to even *be* a step like this: https://github.com/mysociety/verification-pages/issues/180

**Comment by tmtmtmtm** [comment]
My understanding is that this will now only appear in "legacy" where a claim entered this statement before #180 was deployed. If so, we can probably now close this, but I'm not convinced enough that this is actually the case to do so myself (@mhl @chrismytton ?)

**Comment by mhl** [comment]
Yes, I think this is done :+1:
