### ISSUE TITLE
deploy onto WMF toolforge

### ISSUE THREAD

**Issue by mhl** [mysociety/verification-pages#7]
See also #20 

This existing example is probably helpful:

* https://wikitech.wikimedia.org/wiki/Tool:Prompter

And docs on how to create a MySQL database on toolforge I think are here:

* https://wikitech.wikimedia.org/wiki/Help:Toolforge/Database#Steps_to_create_a_user_database_on_tools.db.svc.eqiad.wmflabs

**Comment by mhl** [comment]
Make sure we take backups or know how to access them.

**Comment by chrismytton** [comment]
As alluded to in the original comment, this will mean switching verification-pages from PostgreSQL to MySQL. I've made a start on this in #63. This seems to be working as expected locally, and the tests are still passing.

Next step is to try deploying #63 to Toolforge. I expect some of the work I did getting the prompts tool deployed there will be useful, that's documented [on the Tool:Prompter page on Wikitech](https://wikitech.wikimedia.org/wiki/Tool:Prompter#Initial_setup).

**Comment by chrismytton** [comment]
This is currently blocked because I'm unable to get the mysql2 gem working inside the Kubernetes docker container on Toolforge. I've opened [this Phabricator ticket](https://phabricator.wikimedia.org/T192566) to hopefully get this resolved.

**Comment by chrismytton** [comment]
This has now been deployed to Toolforge. There are still some outstanding tasks before we can close this issue:

- [ ] Migrate the data over from the Heroku PostgreSQL database into the Toolforge MySQL database.
- [ ] Tidy up the `toolforge` branch in this repo and turn it into a pull request (that's the branch that the Toolforge version is currently running off
- [ ] Document the tool, similarly to [Tool:Prompter](https://wikitech.wikimedia.org/wiki/Tool:Prompter), probably at https://wikitech.wikimedia.org/wiki/Tool:Verification_pages
- [ ] Make sure the config in `~/verification-pages/environment_variables.sh` on Toolforge matches what's on Heroku (`heroku config --app verification-pages`)

**Comment by chrismytton** [comment]
Pull request for the Toolforge changes is here: https://github.com/mysociety/verification-pages/pull/126
