### ISSUE TITLE
Hide “You can contribute…” instruction box when verification.js runs

### ISSUE THREAD

**Issue by zarino** [mysociety/verification-pages#70]
There’s no need to tell people how to add the `verification.js` script to their user profile when we know they’ve _already_ added the `verification.js` script to their user profile.

![screen shot 2018-04-05 at 12 56 42](https://user-images.githubusercontent.com/739624/38364478-d32cb070-38d0-11e8-93ff-c63342159fd6.png)

**Comment by zarino** [comment]
I assume this is kinda tricky, because the info box exists _outside_ our vue.js app. So we’ll need something somewhere that just finds the first `.layouttemplate.plainlinks` element after `.js-verification-tool` and hides it.

I have a feeling @markl or @gbp will have a better idea than me as to where this little bit of code should go.

**Comment by gbp** [comment]
I would implement this after the Vue application has been initialised [here](https://github.com/mysociety/verification-pages/blob/master/app/javascript/packs/verification_tool.js#L11).
