### ISSUE TITLE
Make it clearer what “Search” button will do (when returning to a statement that has already been “verified” and is now “reconcilable”)

### ISSUE THREAD

**Issue by zarino** [mysociety/verification-pages#71]
After you’ve “verified” a statement (and it’s showing as “reconcilable”) the only button visible is a blue “Search” button. It’s not very obvious what will happen if you press this button, or why you should press it.

Perhaps the button could be better worded?

And/or perhaps there could be more explanation on the screen you see _after_ you press the button, to make it clearer that you’re meant to pick the person from the resulting list?

Related to #49 – Ideally we could reduce the number of times people see this “Search” button _at all_ by _automatically_ searching after they’ve verified a statement. That way, the “Search” button would only be seen when you’re returning to a statement that has previously been “verified”, but then left, by someone else.

**Comment by tmtmtmtm** [comment]
I think this is fixed / superseded by the changes at 0bb720a86c4d08c179eee03654df80f236699a89
