### ISSUE TITLE
“This statement can’t be actioned automatically” message isn’t very helpful

### ISSUE THREAD

**Issue by zarino** [mysociety/verification-pages#81]
The “This statement can’t be actioned automatically and will need to be done manually” message is not very helpful.

Are we actually expecting the *same* user to get a statement into this state and then manually fix it? Or should we just thank the user for their time, and flag the statement up for an admin to finish off?

If we’re expecting the same user to fix it themselves, why don’t we show the data they actually need to add?

**Comment by mhl** [comment]
Yes, we definitely should show in the interface what the problems are here. These are typicaly contradictions between the P39 in Wikidata and the statement from suggestions-store, and some other cases (e.g. I'd like to add the case where there are multiple matching P39 statements so we don't know which one to apply)
