### ISSUE TITLE
Wikidata can't search with hon. in title or missing apostrophes for example

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/verification-pages#97]
Couldn't think of a succinct way to describe the issue, but basically there are names that are otherwise right, just contain Hon. or lack an apostrophe (for example) but we can't reconcile them on Wikidata because we'd verified them before the option to change the name existed. Wikidata can search but it doesn't bring up the right person because of the extra or missing items. 

Examples:

![screen shot 2018-05-15 at 15 22 00](https://user-images.githubusercontent.com/4170351/40062995-4d409d16-5854-11e8-8792-63d7f6e11483.png)

![screen shot 2018-05-15 at 15 22 11](https://user-images.githubusercontent.com/4170351/40063014-50d4e2ca-5854-11e8-911b-e126affd4643.png)

**Comment by JenMysoc** [comment]
example of what you get if you search on the Hon. Steve Blaney (who is otherwise right)

![screen shot 2018-05-15 at 15 26 50](https://user-images.githubusercontent.com/4170351/40063106-7d4d9964-5854-11e8-8a47-f92ac772b478.png)

**Comment by mhl** [comment]
To link these up, #96 suggests a fix for the "Hon." cases

**Comment by tmtmtmtm** [comment]
I think this is fixed by #355
